### ISSUE TITLE
Suggestion: make it an addon like bunyan-format

### ISSUE THREAD

**Issue by loopdtw** [philmander/browser-bunyan#12]
This way we can use it for universal javascript applications and choose how we would like to stream it depending on environment

https://github.com/thlorenz/bunyan-format

**Comment by philmander** [comment]
I'm not sure what you mean. Bunyan-format is a stream, whereas Browser Bunyan is the core library.

Can you be more specific?

**Comment by loopdtw** [comment]
@philmander since we're using the regular bunyan in a javascript universal app, using a fork would thus make it so that a user would have to have both bunyan + browser-bunyan in order to make it work. 

It would make sense to extract just the stream aspects of it `stream: new ConsoleFormattedStream()` so that the streams can be chosen per environment.

**Comment by philmander** [comment]
So you would like `ConsoleFormattedStream` to be released as an independent module?

**Comment by philmander** [comment]
This is now a thing:

`npm i @browser-bunyan/console-formatted-stream`
