### ISSUE TITLE
Can't Import ServerStream

### ISSUE THREAD

**Issue by tempo123456** [philmander/browser-bunyan#15]
Hello,

When I try to import { ServerStream } from '@browser-bunyan/server-stream'; , I get an error saying "Error: Cannot find module '@browser-bunyan/server-stream'"

**Comment by philmander** [comment]
Did you install it?

**Comment by tempo123456** [comment]
Yup I ran 'npm install browser-bunyan --save', also when I look at the browser-bunyan index.js file I do not see an export for '@browser-bunyan/server-stream', so that could be the problem? I can import the ConsoleFormattedStream and the ConsoleRawStream no problem, and I can send a log to the client. Also, when I check the dependencies of my package.json, I do not see "@browser-bunyan/server-stream", but the file does contain "@browser-bunyan/console-formatted-stream", "@browser-bunyan/console-raw-stream", "@browser-bunyan/levels".

**Comment by philmander** [comment]
You need to install server stream specifically:

`npm install @browser-bunyan/server-stream`

Try that. I should have made that clearer in the docs

**Comment by kcirone** [comment]
I have tried using both installed and unpkg.com version of server-stream and still cannot seem to use the object.  Using code such as:

`
...
<head>
		<script src="https://unpkg.com/browser-bunyan@1.5.0/lib/index.umd.js"></script>
		<script src="https://unpkg.com/@browser-bunyan/server-stream@1.5.0/lib/index.umd.js"></script>
</head>
...
<script>
var _baseLogger = bunyan.createLogger({
	name: 'myLog',
	streams: [
		{
            level: "info",
            stream: new bunyan.ServerStream({
                url: 'http://localhost:3000/log',
                method: 'POST',
                flushOnClose: true
            })
		}
	]
});
...
</script>
`
I continue to get the error:

`bunyan.ServerStream is not a constructor`

The script using browser-bunyan is inline in an HTML file if that matters.  Thoughts?

**Comment by kcirone** [comment]
I can't seem to import ServerStream using either an installed or the unpkg.com version of the files.
Imports: 
`<script src="https://unpkg.com/browser-bunyan@1.5.0/lib/index.umd.js"></script>`
`<script src="https://unpkg.com/@browser-bunyan/server-stream@1.5.0/lib/index.umd.js"></script>`

Code in HTML file (inline script element):

`var _baseLogger = bunyan.createLogger({`
`	name: 'myLog',`
`	streams: [`
`		{`
`            level: "info",`
`            stream: new bunyan.ServerStream({`
`                url: 'http://localhost:3000/log',`
`                method: 'POST',`
`				flushOnClose: true,`
`				writeCondition: record => {return true;} //for now`
`            })`
`		}`
`	]`
`});`

I get the error

`bunyan.ServerStream is not a constructor`

Thoughts?

**Comment by kcirone** [comment]
Sorry, deleted the question before I saw your answer.  Thanks!
