### ISSUE TITLE
types

### ISSUE THREAD

**Issue by veeramarni** [philmander/browser-bunyan#16]
Do the [types link](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/browser-bunyan/index.d.ts) still valid for `v1.3.0`?

**Comment by philmander** [comment]
Possibly not. It's not something that's been part of my testing process.

**Comment by nyn3x** [comment]
Because of the change of the namespace for the console-formatted-stream (and others) this isn't working anymore.

This currently blocks me from evaluating browser-bunyan in my current project 🙁

**Comment by philmander** [comment]
I have waited a long and lonely 2 years for the open source community to fix this, alas with no joy. 

But finally I've added typings as part of the project in v1.6.0. @nyn3x you are now unblocked and free to enjoy browser bunyan!

Please let me know if anything is not working properly

**Comment by nyn3x** [comment]
just upgraded my project ... awesome!

**Comment by Poky85** [comment]
@philmander Good work!

To be honest I created draft of browser-bunyan types few months ago (as DefinitelyTyped fork), but have never had time to finish it.

**There is pretty accurate definition of `browser-bunyan` package I think**
https://github.com/Poky85/DefinitelyTyped/blob/browser-bunyan/types/browser-bunyan/index.d.ts

I'll try to make a PR with some improvements when I find some time.
