### ISSUE TITLE
browser-bunyan.min.js missing bunyan.ServerStream

### ISSUE THREAD

**Issue by karcliew** [philmander/browser-bunyan#18]
Hi, 
For `<script src="//unpkg.com/browser-bunyan@1.3.0/dist/browser-bunyan.min.js"></script>`, I am able to instantiate `bunyan.ConsoleRawStream` and `ConsoleRawStream.ConsoleFormattedStream` but not `bunyan.ServerStream`.  Can we have `bunyan.ServerStream` package into `browser-bunyan.min.js`?

Thanks

**Comment by philmander** [comment]
I didn't want to make it part of the core package, but if you include: 

`<script src="https://unpkg.com/@browser-bunyan/server-stream@1.3.0/lib/index.umd.js"></script>`

you can load the server stream as you want.

I will try and document this too.

**Comment by karcliew** [comment]
Thank you. I appreciate the response.

**Comment by philmander** [comment]
The docs now reflect this
