### ISSUE TITLE
Color cannot support

### ISSUE THREAD

**Issue by L-Jovi** [philmander/browser-bunyan#19]
I apply your default css by using `new ConsoleFormattedStream` while notice that some color cannot support, all format display failed.

![image](https://user-images.githubusercontent.com/7262199/43111301-213eee10-8f23-11e8-81fa-bb337fb0cc61.png)

And how should I fix it?

Thanks for your time.

**Comment by philmander** [comment]
Only certain browsers support [styling with colours in the console](https://developers.google.com/web/tools/chrome-devtools/console/console-write#styling_console_output_with_css).

You can use the built-in `ConsoleRawStream` instead or write your own custom log stream. See the streams into this codebase for examples.

However, it did occur to me that Browser Bunyan should probably ship with a `ConsolePlainStream` out of the box, so I will try and add one this evening.

Thanks for sharing this issue.

**Comment by L-Jovi** [comment]
Thanks for your reply :)

It's smart logger in browser side.

**Comment by philmander** [comment]
You can now try `ConsolePlainStream` in v1.4.0

git@github.com:philmander/browser-bunyan.git
