### ISSUE TITLE
How to reserve error stack

### ISSUE THREAD

**Issue by L-Jovi** [philmander/browser-bunyan#21]
Hi, thanks for your smart browser logger.

I implement simple custom class which call your logger behaviour as below image show.

__utils/logger.js__

![image](https://user-images.githubusercontent.com/7262199/43751287-dba90c16-9a2e-11e8-86ef-16720068414a.png)

But I notice the error stack output which locate to my class instead of real position.

![image](https://user-images.githubusercontent.com/7262199/43751394-4b7c0af2-9a2f-11e8-8e22-e1424ccc0407.png)

If I want to reserve error stack from my logic caller (like my app.js) instead of my custom logger.js, how should I implement it?

Thanks for your time,

regards.

**Comment by philmander** [comment]
Hi L-Jovi - Glad you find it useful

I think your question is a dup of https://github.com/philmander/browser-bunyan/issues/7. It's been open for a while because I'm not really sure how to solve this issue

**Comment by L-Jovi** [comment]
@philmander  Thanks for your reply, I'll refer to issue #7, close dup :)
