### ISSUE TITLE
Document childName field

### ISSUE THREAD

**Issue by brucejo75** [philmander/browser-bunyan#26]
When creating a child logger a `childName` field can be passed and utilized by [`console-formatted-stream`](https://github.com/philmander/browser-bunyan/blob/master/packages/console-formatted-stream/src/index.js#L29),

This appears to be undocumented.

I was in the process of creating my own version of `console-formatted-stream` when I discovered this.

**Comment by philmander** [comment]
Docs on child loggers are here: https://github.com/philmander/browser-bunyan/blob/master/README.md#logchild

Bunyan has lots of goodies that are usually represented somehow in a stream

**Comment by philmander** [comment]
I'm not actually sure why this is there! You would have to add a `childName` to every log statement right? Not very nice.

**Comment by brucejo75** [comment]
You only need to add it when you create the child:

```javascript
childLog = Meris.log.child({'childName': 'child'});
childLog.info('foobar')
```

outputs:
```console
[14:58:23:0865]  INFO: myapp/child: foobar
```

**Comment by philmander** [comment]
Finally fixed!
