### ISSUE TITLE
a condition inside server stream will never get called

### ISSUE THREAD

**Issue by vidarc** [philmander/browser-bunyan#27]
https://github.com/philmander/browser-bunyan/blob/3d92bc98505bd321a13d59999e068571943404db/packages/server-stream/src/index.js#L27

line needs to be either
```javascript
method.toLowerCase() === 'post'
```
or
```javascript
method.toUpperCase() === 'POST'
```

**Comment by philmander** [comment]
Fix in https://github.com/philmander/browser-bunyan/pull/28
