### ISSUE TITLE
Angular example in documentation is incomplete

### ISSUE THREAD

**Issue by kibertoad** [philmander/browser-bunyan#3]
"var bunyan = require('./lib/bunyan');" as given in the documentation example is NodeJS code, you cannot use that in browser. Hence the provided example of

<...>
$delegate = bunyan.createLogger({
<...>

is extremely unclear - where does the "bunyan" instance come from? When I attempt to inject "bunyan" or "browser-bunyan" into my Angular module, I get "Module 'bunyan' (or "browser-bunyan") is not available!" errors.

Could you please clarify documentation regarding how it's supposed to be done?

**Comment by philmander** [comment]
Thanks for pointing that out, I'll make the docs more clear. 

Browser Bunyan is exported as a [UMD](https://github.com/umdjs/umd) module. In the simplest case you just include it using a script tag and use `bunyan` as a global variable. You can use the `require` syntax if you're using Browserify or Webpack

**Comment by philmander** [comment]
I've added some more docs on installation and usage. Hopefully the extreme lack of clarity has been rectified.
