### ISSUE TITLE
No option for flushOnNavigate

### ISSUE THREAD

**Issue by bradly-fairbanks** [philmander/browser-bunyan#30]
We have a requirement that we'd like to have the logs sent back to the server when a user changes pages. It looks like the library supports dumping the logs when the user closes the tab or window via the `unload` event, and we'd like to add in the option to dump them via the `beforeunload` event as well. 

We are fine to make the change, however we have a lengthy review process we have to go through in order to contribute to open source projects. So before we go through that process we'd like to verify that A) this isn't already being worked on and B) this is a change that would be a welcome addition to the library.

**Comment by philmander** [comment]
Hi Bradley, I believed that the current approach in `ServerStream`, using `navigator.sendBeacon` should work if either the page is closed or navigated away from (IE11 is not supported; for this I think you would need to send an xhr on beforeunload although I'm not sure how reliable that is).

Are you sure the current code does not run when navigating away? If so, we can discuss the solution some more here before submitting code to verify it is welcome.

Either way, Browser Bunyan streams are very pluggable. You can always work from the `ServerStream` code to create a custom stream as a standalone project which you can host separately or use internally within your organisation.

**Comment by bradly-fairbanks** [comment]
Yeah, we though it would trigger on both a page close and a navigate but have verified twice that it does not trigger. ¯\\_(ツ)_/¯

We are fine to add the functionality locally within our project, we just wanted to try and be good open source consumers and check with you to see if it was something you would want included in your project. So we're fine either way.

**Comment by philmander** [comment]
So what's the solution?
