### ISSUE TITLE
Is jest not running ServerStream?

### ISSUE THREAD

**Issue by 9bits** [philmander/browser-bunyan#32]
```
export function myLogger(): void {
    const logger = createLogger({
        name: 'myLogger',
        level: INFO, 
        stream: new ServerStream({
            url: 'http://0.0.0.0:8080/sandbox',
            method: 'POST'
        }),
    });
    logger.info("testtest"); 
}
```

I have this basic implementation of ServerStream, and I'm trying to write a test to check that ServerStream is actually working. 

However, when I run the jest test, I realize that my endpoint never gets hit when the test is running. 

However, when I run this function normally, I am able to see that the endpoint is hit

Is this an expected behavior?

**Comment by philmander** [comment]
Hi Jon, the jest test that exists is a unit test. A good unit test should not rely on any external dependencies like a server. Instead, it overrides the behavior of `XMLHttpRequest` to mock expected server behavior. 

Look for `MockXMLHttpRequest` in https://github.com/philmander/browser-bunyan/blob/master/packages/server-stream/test/server-stream.test.js

**Comment by philmander** [comment]
I also just realized that ServerStream's unit test doesn't actually run on Jest, but another testing framework, Tap.

**Comment by 9bits** [comment]
Yeah, I was had set up jest mocks but the assert for XMLHttpRequest kept failing. I realized that ServerStream wasn't getting used when the test was run when I checked if the endpoint was getting hit

**Comment by philmander** [comment]
Do you still need some help with this?

**Comment by 9bits** [comment]
Yeah, I'm still wondering if it's possible to use jest to test this use case.
I'm also trying to figure out why jest doesn't even try to initialize ServerStream.

**Comment by philmander** [comment]
I originally thought you were trying to write a Jest based test for `ServerStream` directly, but I think you are trying to test your code that uses a logger configured to use `ServerStream`. You have to options:

- To proceed with your current approach, you need to globally mock `XMLHttpRequest`. Maybe there's some issues around doing this in Jest, I'm not sure
- I would alternatively recommend that you find a way to completely mock your Bunyan logger in your tests or a logger without any Streams added
