### ISSUE TITLE
[ConsoleFormattedStream]: Log objects to the same console line as the log output

### ISSUE THREAD

**Issue by brucejo75** [philmander/browser-bunyan#36]
When [logging objects](https://github.com/philmander/browser-bunyan#logging-objects-to-the-console), the object is output on the line following the formatted text output.

This is pretty much fine when reading through the logs.  But when using console filter/find features it is a total pain.  Because the object is output on the next line and it is not available in the search results.

### Workaround
It is pretty simple to modify[ `ConsoleFormattedStream`](https://github.com/philmander/browser-bunyan/blob/master/packages/console-formatted-stream/src/index.js#L75-L87) to output the object on the same line.

```diff
        if (rec.src) {
             logArgs.push(srcCss);
             logArgs.push(rec.src);
         }
+        if (rec.obj) {
+          logArgs.push(rec.obj);
+      }

         consoleMethod.apply(console, logArgs);
         if (rec.err && rec.err.stack) {
             consoleMethod.call(console, '%c%s,', levelCss, rec.err.stack);
         }
-        if (rec.obj) {
-            consoleMethod.call(console, rec.obj);
-        }
```

**Comment by philmander** [comment]
Thanks for the suggestion, Available in v1.6.2
