### ISSUE TITLE
flushOnClose sends records as text/plain instead of application/json

### ISSUE THREAD

**Issue by 9bits** [philmander/browser-bunyan#44]
I noticed that when flushOnClose is on, browser-bunyan's ServerStream seems to be sending out the records with content-type set as `text/plain` instead of `application/json`. 

https://github.com/philmander/browser-bunyan/blob/bafd4c9d9a196a19dc1bbb4fe9507900d66d8387/packages/server-stream/src/index.js#L34

Is this intentional?

I've been accepting application/json from browser-bunyan and I've been seeing 415 errors because of invalid content-type.

Thanks!

**Comment by philmander** [comment]
Yes, this is deliberate. See: https://github.com/philmander/browser-bunyan#notes

However, the reasons for doing so may well be out of date

**Comment by 9bits** [comment]
Thanks. Are there any plans to change this?

I'd like to know your considerations for changing `text/plain` to `application/json`

**Comment by philmander** [comment]
I've updated this and it works as far as I can see. `@1.6.1`
