### ISSUE TITLE
Removal of streams

### ISSUE THREAD

**Issue by nyn3x** [philmander/browser-bunyan#57]
Hi,

I have added seq (via [bunyan-seq](https://www.npmjs.com/package/bunyan-seq)) to my bunyan-browser config to send message to a server. However, when the server is not available bunyan-browser throws an error.

I already registered an onError handler to the my stream, but that just shows, a message to the console that an error occured. I would like to remove the stream from my logger to avoid further error, especially failures in my app, due to a not reachable stream.

Is there any way to remove a stream from an existing logger?

**Comment by philmander** [comment]
There isn't a public interface for this , but you can do this:

```js
const streamToRemove = new bunyan.ConsoleRawStream();

const logger = bunyan.createLogger({
  name: 'logger',
  streams: [{
    level: 'trace',
    stream: streamToRemove,
  }]
});

const i = rawLogger.streams.findIndex(s => s.stream === streamToRemove);
logger.streams.splice(i, 1);
```
