### ISSUE TITLE
Maintenance status and divergence from (server-side) bunyan

### ISSUE THREAD

**Issue by rmharrison** [philmander/browser-bunyan#6]
Hey @philmander, 

Looks like there has been additional divergence and bug fixes between bunyan and browser-bunyan since https://github.com/philmander/browser-bunyan/issues/4 last year.

Are there any plans to bring in changes from bunyan? Wondering if this npm module is maintained/safe to use, or whether I should just accept a bit of bloat from a browersfied bunyan ~and excerpt `ConsoleFormattedStream` from brower-bunyan~ (failed because of divergence between browersfied bunyan and browser-bunyan).

**Comment by philmander** [comment]
Hi Ryan,

I know its been a while since any updates, but I haven't seen any new features or issues in node-bunyan itself which need to be ported (maybe [#469](https://github.com/trentm/node-bunyan/pull/469)?). Neither have any issues or PRs come in. So it seems to be in "if it ain't broke, don't fix it" mode at the moment. Also, as I mentioned in #4 I don't plan on rebasing node-bunyan now, since the codebase has diverged too much.

If any new issues or PR's are made, I will be actively looking at them; or if there are any new node-bunyan features which need porting into this project. I have also been thinking recently that it might be nice to modernize the code a bit (more ES6 and see if I can get the bundle size smaller). Any requests or suggestions are welcome.

So, to answer your question, it's as safe as it has ever been to use this, so I don't see why you shoudn't.

**Comment by rmharrison** [comment]
Thanks so much for the prompt response. Will give a whirl.

Two notes...

1. `src` shows the compiled location, as opposed to the location in the sourcemap.
```
Class.updateCount (http://localhost:4200/assets/project-assets.js:1382:12) bunyan.js:259
```

2. `browser-bunyan` has diverged enough from `bunyan`, that `browser-bunyan::ConsoleFormattedStream(req)` can't be copy/paste excerpted for bunyan use.

Expected behavior?

**Comment by philmander** [comment]
1. No idea off the top of my head. I'd need to look into it further. Could you raise a separate issue?

2. It works, but there are a few variables referenced via closure, which need to be on the bunyan namespace when outside of the Bunyan source. These are `nameFromLevel` --> `bunyan.nameFromLevel` and the log level constants: `TRACE`, `DEBUG`, `WARN`, `INFO`, `ERROR` and `FATAL` --> `bunyan.TRACE` etc. 

    More generally on this point, although the code has diverged internally, the interfaces of supported features have/will not change.

    You also need to ensure you're using a *raw* stream. Only raw streams make sense in the browser, so `raw` is true by default in browser-bunyan, but not in node-bunyan. 

    Here's some working code adapted from the node-bunyan browserify example:

```javascript
var bunyan = require('bunyan');

function ConsoleFormattedStream(opts) {
    opts = opts || {};
    this.logByLevel = !!opts.logByLevel;
}
ConsoleFormattedStream.prototype.write = function (rec) {

    var levelCss,
        defaultCss = 'color: DimGray',
        msgCss = 'color: SteelBlue',
        srcCss = 'color: DimGray; font-style: italic; font-size: 0.9em',
        consoleMethod;

    var loggerName = rec.childName ? rec.name + '/' + rec.childName : rec.name;

    //get level name and pad start with spacs
    var levelName = bunyan.nameFromLevel[rec.level];
    var formattedLevelName = (Array(6 - levelName.length).join(' ') + levelName).toUpperCase();

    if(this.logByLevel) {
        if(rec.level === bunyan.TRACE) {
            levelName = 'debug';
        } else if(rec.level === bunyan.FATAL) {
            levelName = 'error';
        }
        consoleMethod = typeof console[levelName] === 'function' ? console[levelName] : console.log;
    } else {
        consoleMethod = console.log;
    }

    if (rec.level < bunyan.DEBUG) {
        levelCss = 'color: DeepPink';
    } else if (rec.level < bunyan.INFO) {
        levelCss = 'color: GoldenRod';
    } else if (rec.level < bunyan.WARN) {
        levelCss = 'color: DarkTurquoise';
    } else if (rec.level < bunyan.ERROR) {
        levelCss = 'color: Purple';
    } else if (rec.level < bunyan.FATAL) {
        levelCss = 'color: Crimson';
    } else {
        levelCss = 'color: Black';
    }

    function padZeros(number, len) {
        return Array((len + 1) - (number + '').length).join('0') + number;
    }

    var logArgs = [];
    logArgs.push('[%s:%s:%s:%s] %c%s%c: %s: %c%s');
    logArgs.push(padZeros(rec.time.getHours(), 2));
    logArgs.push(padZeros(rec.time.getMinutes(), 2));
    logArgs.push(padZeros(rec.time.getSeconds(), 2));
    logArgs.push(padZeros(rec.time.getMilliseconds(), 4));
    logArgs.push(levelCss);
    logArgs.push(formattedLevelName);
    logArgs.push(defaultCss);
    logArgs.push(loggerName);
    logArgs.push(msgCss);
    logArgs.push(rec.msg);
    if(rec.src) {
        logArgs.push(srcCss);
        logArgs.push(rec.src);
    }

    consoleMethod.apply(console, logArgs);
    if(rec.err && rec.err.stack) {
        consoleMethod.call(console, '%c%s,', levelCss, rec.err.stack);
    }
    if(rec.obj) {
        consoleMethod.call(console, rec.obj);
    }
};

var log = bunyan.createLogger({
	name: 'play',
	 level: 'debug',
	streams: [
        {
            level: 'debug',
            stream: new ConsoleFormattedStream(),
            type: 'raw'
        }
]});

log.trace('this one does not emit');
log.debug('hi on debug');   // console.log
log.info('hi on info');     // console.info
log.warn('hi on warn');     // console.warn
log.error('hi on error');   // console.error
```
