### ISSUE TITLE
Can we return result of executing "write" methods of streams?

### ISSUE THREAD

**Issue by maksym-leichenko** [philmander/browser-bunyan#68]
I want to create `SentryStream` and this stream will send fatal errors to [sentry](https://sentry.io/).
Sentry has the ability to return `issue id` - I want somehow to get this ID.

----

Could we just return an array of results of executing `write` methods?
Like this https://github.com/philmander/browser-bunyan/pull/67

----

Will work like this:
```
export class SentryStream {
    write(rec) {
        // send error to Sentry
        const id = "...." // some Sentry Issue ID
        return id;
    }
}

```

```
const result = logger.fatal(new Error('some error'));
console.log(result); // ["...sentry-issue-id..."] 
```

**Comment by philmander** [comment]
This feels a bit wrong to change the common interface for this specific case.

Might be a better idea to make the SentryStream observable by extending something like (`EventEmitter`)[https://nodejs.org/api/events.html#class-eventemitter] and have it emit events containing sentry ID's?

I'm not sure how Sentry works, but if getting the ID is an async call, this would play better with that too
