### ISSUE TITLE
Support sourcemap locations like `console.log`?

### ISSUE THREAD

**Issue by rmharrison** [philmander/browser-bunyan#7]
Currently, bunyan's `req.src` shows the compiled location (an asset bundle), as opposed to the location in the sourcemap.

## browser-bunyan
```
// ConsoleFormattedStream
... Class.updateCount (http://localhost:4200/assets/project-assets.js:1382:12) bunyan.js:259
```

```
// stdout
...
src: "Class.updateCount (http://localhost:4200/assets/project-assets.js:1382:12)"
```

NB: Asset compilation was performed via Broccoli (ember-cli build pipeline)

## console.log
```
log message   local-file.js.js:93
```

NB: Identical behavior between browerified node-bunyan and browser-bunyan

**Comment by markabrahams** [comment]
Hi @philmander - just tried browser-bunyan today for an Angular project, and just wanted to say well done for the good work here!

It works and looks great for my Angular app, but unfortunately this issue prevents me from being able to use it, as a log message lacks the source code line that logged it, which is critical information for me when looking at logs.

Really like the project anyway, so have given it a star! :-)
