### ISSUE TITLE
is there an server implementation?

### ISSUE THREAD

**Issue by gengshenghong** [philmander/browser-bunyan#73]
Thank you for this project. I read the docs and it support send the logs to a server endpoint. But I did not find any server implementation details, is there an existing implementation or we need to implement a simple server endpoint to receive the logs manually (it seems not very difficult though).

Thanks,
Shenghong

**Comment by philmander** [comment]
Hi @gengshenghong. Yes, implementing a server endpoint will likely be quite specific to your set up, so it's not really useful to provide one. You are correct though, it should be quite simple.

However, there is a very simple Node.JS one, for manual testing, here: https://github.com/philmander/browser-bunyan/blob/master/examples/browser/server.js
